[workspace]
name = "usbip-gui"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]
version = "1.2.0"

[dependencies]
python = ">=3.10"

[pypi-dependencies]
PyQt6 = "*"

[feature.dev.dependencies]
flake8 = "*"
black = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
pyright = ">=1.1.411,<2"
mypy = "*"

[environments]
default = ["dev"]
[tasks]
usbip = "python3 -m usbip_gui.main"
lint = "python3 -m flake8 . && python3 -m pylint . && python3 -m pyright . && python3 -m mypy ."
format = "python3 -m black ."
test = { cmd = "PYTHONPATH=. python3 -m pytest tests/ -v --cov=usbip_gui --cov-report=html --cov-report=term", env = { QT_QPA_PLATFORM = "offscreen" } }
