import usb.core as core

__all__ = ['get_status', 'clear_feature', 'set_feature', 'get_descriptor', 'set_descriptor', 'get_configuration', 'set_configuration', 'get_interface', 'set_interface', 'ENDPOINT_HALT', 'FUNCTION_SUSPEND', 'DEVICE_REMOTE_WAKEUP', 'U1_ENABLE', 'U2_ENABLE', 'LTM_ENABLE']

USBError = core.USBError
ENDPOINT_HALT: int
FUNCTION_SUSPEND: int
DEVICE_REMOTE_WAKEUP: int
U1_ENABLE: int
U2_ENABLE: int
LTM_ENABLE: int

def get_status(dev, recipient=None): ...
def clear_feature(dev, feature, recipient=None) -> None: ...
def set_feature(dev, feature, recipient=None) -> None: ...
def get_descriptor(dev, desc_size, desc_type, desc_index, wIndex: int = 0): ...
def set_descriptor(dev, desc, desc_type, desc_index, wIndex=None) -> None: ...
def get_configuration(dev): ...
def set_configuration(dev, bConfigurationNumber) -> None: ...
def get_interface(dev, bInterfaceNumber): ...
def set_interface(dev, bInterfaceNumber, bAlternateSetting) -> None: ...
