import usb._objfinalizer as _objfinalizer
from _typeshed import Incomplete
from typing import Callable, List, Literal, Optional, TypeVar, overload

_F = TypeVar("_F", bound=object)

def synchronized(fn: _F) -> _F: ...

__all__ = ['Device', 'Configuration', 'Interface', 'Endpoint', 'USBError', 'USBTimeoutError', 'NoBackendError', 'find', 'show_devices']

class _DescriptorInfo(str): ...

class _ResourceManager:
    backend: Incomplete
    dev: Incomplete
    handle: Incomplete
    lock: Incomplete
    def __init__(self, dev, backend) -> None: ...
    @synchronized
    def managed_open(self): ...
    @synchronized
    def managed_close(self) -> None: ...
    index: Incomplete
    bConfigurationValue: int
    @synchronized
    def managed_set_configuration(self, device, config) -> None: ...
    @synchronized
    def managed_claim_interface(self, device, intf) -> None: ...
    @synchronized
    def managed_release_interface(self, device, intf) -> None: ...
    @synchronized
    def managed_set_interface(self, device, intf, alt) -> None: ...
    @synchronized
    def setup_request(self, device, endpoint): ...
    @synchronized
    def get_interface_and_endpoint(self, device, endpoint_address): ...
    @synchronized
    def get_active_configuration(self, device): ...
    @synchronized
    def release_all_interfaces(self, device) -> None: ...
    @synchronized
    def dispose(self, device, close_handle: bool = True) -> None: ...

class USBError(IOError):
    backend_error_code: Incomplete
    def __init__(self, strerror, error_code=None, errno=None) -> None: ...

class USBTimeoutError(USBError): ...
class NoBackendError(ValueError): ...

class Endpoint:
    device: Incomplete
    index: Incomplete
    def __init__(self, device, endpoint, interface: int = 0, alternate_setting: int = 0, configuration: int = 0) -> None: ...
    def write(self, data, timeout=None): ...
    def read(self, size_or_buffer, timeout=None): ...
    def clear_halt(self) -> None: ...

class Interface:
    device: Incomplete
    alternate_index: Incomplete
    index: Incomplete
    configuration: Incomplete
    def __init__(self, device, interface: int = 0, alternate_setting: int = 0, configuration: int = 0) -> None: ...
    def endpoints(self): ...
    def set_altsetting(self) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, index): ...

class Configuration:
    device: Incomplete
    index: Incomplete
    def __init__(self, device, configuration: int = 0) -> None: ...
    def interfaces(self): ...
    def set(self) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, index): ...

class Device(_objfinalizer.AutoFinalizedObject):
    def __eq__(self, other): ...
    def __hash__(self): ...
    def configurations(self): ...
    bus: Incomplete
    address: Incomplete
    port_number: Incomplete
    speed: Incomplete
    def __init__(self, dev, backend) -> None: ...
    @property
    def langids(self): ...
    @property
    def serial_number(self): ...
    @property
    def product(self): ...
    @property
    def parent(self): ...
    @property
    def manufacturer(self): ...
    @property
    def backend(self): ...
    def set_configuration(self, configuration=None) -> None: ...
    def get_active_configuration(self): ...
    def set_interface_altsetting(self, interface=None, alternate_setting=None) -> None: ...
    def clear_halt(self, ep) -> None: ...
    def reset(self) -> None: ...
    def write(self, endpoint, data, timeout=None): ...
    def read(self, endpoint, size_or_buffer, timeout=None): ...
    def ctrl_transfer(self, bmRequestType, bRequest, wValue: int = 0, wIndex: int = 0, data_or_wLength=None, timeout=None): ...
    def is_kernel_driver_active(self, interface): ...
    def detach_kernel_driver(self, interface) -> None: ...
    def attach_kernel_driver(self, interface) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, index): ...
    default_timeout: Incomplete

@overload
def find(find_all: Literal[False] = ..., backend: Incomplete = ..., custom_match: Incomplete = ..., **args: Incomplete) -> Optional[Device]: ...
@overload
def find(find_all: Literal[True], backend: Incomplete = ..., custom_match: Incomplete = ..., **args: Incomplete) -> List[Device]: ...
def show_devices(verbose: bool = False, **kwargs: Incomplete) -> None: ...
