__all__ = ['LibraryException', 'LibraryNotFoundException', 'NoLibraryCandidatesException', 'LibraryNotLoadedException', 'LibraryMissingSymbolsException', 'locate_library', 'load_library', 'load_locate_library']

class LibraryException(OSError): ...
class LibraryNotFoundException(LibraryException): ...
class NoLibraryCandidatesException(LibraryNotFoundException): ...
class LibraryNotLoadedException(LibraryException): ...
class LibraryMissingSymbolsException(LibraryException): ...

def locate_library(candidates, find_library=...): ...
def load_library(lib, name=None, lib_cls=None): ...
def load_locate_library(candidates, cygwin_lib, name, win_cls=None, cygwin_cls=None, others_cls=None, find_library=None, check_symbols=None): ...
