from ctypes import *
import usb
import usb._objfinalizer as _objfinalizer
from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['get_backend', 'OPENUSB_SUCCESS', 'OPENUSB_PLATFORM_FAILURE', 'OPENUSB_NO_RESOURCES', 'OPENUSB_NO_BANDWIDTH', 'OPENUSB_NOT_SUPPORTED', 'OPENUSB_HC_HARDWARE_ERROR', 'OPENUSB_INVALID_PERM', 'OPENUSB_BUSY', 'OPENUSB_BADARG', 'OPENUSB_NOACCESS', 'OPENUSB_PARSE_ERROR', 'OPENUSB_UNKNOWN_DEVICE', 'OPENUSB_INVALID_HANDLE', 'OPENUSB_SYS_FUNC_FAILURE', 'OPENUSB_NULL_LIST', 'OPENUSB_CB_CONTINUE', 'OPENUSB_CB_TERMINATE', 'OPENUSB_IO_STALL', 'OPENUSB_IO_CRC_ERROR', 'OPENUSB_IO_DEVICE_HUNG', 'OPENUSB_IO_REQ_TOO_BIG', 'OPENUSB_IO_BIT_STUFFING', 'OPENUSB_IO_UNEXPECTED_PID', 'OPENUSB_IO_DATA_OVERRUN', 'OPENUSB_IO_DATA_UNDERRUN', 'OPENUSB_IO_BUFFER_OVERRUN', 'OPENUSB_IO_BUFFER_UNDERRUN', 'OPENUSB_IO_PID_CHECK_FAILURE', 'OPENUSB_IO_DATA_TOGGLE_MISMATCH', 'OPENUSB_IO_TIMEOUT', 'OPENUSB_IO_CANCELED']

OPENUSB_SUCCESS: int
OPENUSB_PLATFORM_FAILURE: int
OPENUSB_NO_RESOURCES: int
OPENUSB_NO_BANDWIDTH: int
OPENUSB_NOT_SUPPORTED: int
OPENUSB_HC_HARDWARE_ERROR: int
OPENUSB_INVALID_PERM: int
OPENUSB_BUSY: int
OPENUSB_BADARG: int
OPENUSB_NOACCESS: int
OPENUSB_PARSE_ERROR: int
OPENUSB_UNKNOWN_DEVICE: int
OPENUSB_INVALID_HANDLE: int
OPENUSB_SYS_FUNC_FAILURE: int
OPENUSB_NULL_LIST: int
OPENUSB_CB_CONTINUE: int
OPENUSB_CB_TERMINATE: int
OPENUSB_IO_STALL: int
OPENUSB_IO_CRC_ERROR: int
OPENUSB_IO_DEVICE_HUNG: int
OPENUSB_IO_REQ_TOO_BIG: int
OPENUSB_IO_BIT_STUFFING: int
OPENUSB_IO_UNEXPECTED_PID: int
OPENUSB_IO_DATA_OVERRUN: int
OPENUSB_IO_DATA_UNDERRUN: int
OPENUSB_IO_BUFFER_OVERRUN: int
OPENUSB_IO_BUFFER_UNDERRUN: int
OPENUSB_IO_PID_CHECK_FAILURE: int
OPENUSB_IO_DATA_TOGGLE_MISMATCH: int
OPENUSB_IO_TIMEOUT: int
OPENUSB_IO_CANCELED: int

class _usb_endpoint_desc(Structure): ...
class _usb_interface_desc(Structure): ...
class _usb_config_desc(Structure): ...
class _usb_device_desc(Structure): ...
class _openusb_request_result(Structure): ...

class _openusb_ctrl_request(Structure):
    payload: Incomplete
    length: int
    timeout: int
    flags: int
    next: Incomplete
    def __init__(self) -> None: ...
    class _openusb_ctrl_setup(Structure): ...

class _openusb_intr_request(Structure): ...
class _openusb_bulk_request(Structure): ...

class _openusb_isoc_pkts(Structure):
    class _openusb_isoc_packet(Structure): ...

class _openusb_isoc_request(Structure): ...

class _Context(_objfinalizer.AutoFinalizedObject):
    handle: Incomplete
    def __init__(self) -> None: ...

class _BusIterator(_objfinalizer.AutoFinalizedObject):
    buslist: Incomplete
    num_busids: Incomplete
    def __init__(self) -> None: ...
    def __iter__(self): ...

class _DevIterator(_objfinalizer.AutoFinalizedObject):
    devlist: Incomplete
    num_devids: Incomplete
    def __init__(self, busid) -> None: ...
    def __iter__(self): ...

class _OpenUSB(usb.backend.IBackend):
    def enumerate_devices(self) -> Generator[Incomplete]: ...
    def get_device_descriptor(self, dev): ...
    def get_configuration_descriptor(self, dev, config): ...
    def get_interface_descriptor(self, dev, intf, alt, config): ...
    def get_endpoint_descriptor(self, dev, ep, intf, alt, config): ...
    def open_device(self, dev): ...
    def close_device(self, dev_handle) -> None: ...
    def set_configuration(self, dev_handle, config_value) -> None: ...
    def get_configuration(self, dev_handle): ...
    def set_interface_altsetting(self, dev_handle, intf, altsetting) -> None: ...
    def claim_interface(self, dev_handle, intf) -> None: ...
    def release_interface(self, dev_handle, intf) -> None: ...
    def bulk_write(self, dev_handle, ep, intf, data, timeout): ...
    def bulk_read(self, dev_handle, ep, intf, buff, timeout): ...
    def intr_write(self, dev_handle, ep, intf, data, timeout): ...
    def intr_read(self, dev_handle, ep, intf, buff, timeout): ...
    def ctrl_transfer(self, dev_handle, bmRequestType, bRequest, wValue, wIndex, data, timeout): ...
    def reset_device(self, dev_handle) -> None: ...
    def clear_halt(self, dev_handle, ep) -> None: ...

def get_backend(find_library=None): ...
