name: Test and Lint Checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test-and-lint-ubuntu:
    name: Test and Lint Checks (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true
          locked: false
          manifest-path: pixi.toml

      - name: Install Qt system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pyqt6 xvfb

      - name: Run Black Formatting Check
        run: pixi run black --check .

      - name: Run Flake8
        run: pixi run flake8 .

      - name: Run Pylint
        run: pixi run pylint usbip_gui

      - name: Run Pyright
        run: pixi run pyright .

      - name: Run Mypy
        run: pixi run mypy .

      - name: Run Pytest
        run: pixi run test

  test-and-lint-windows:
    name: Test and Lint Checks (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true
          locked: false
          manifest-path: pixi.toml

      - name: Run Windows installer script
        shell: cmd
        run: echo.| win_installers\install_windows.bat

      - name: Run Black Formatting Check
        run: pixi run black --check .

      - name: Run Flake8
        run: pixi run flake8 .

      - name: Run Pylint
        run: pixi run pylint usbip_gui

      - name: Run Pyright
        run: pixi run pyright .

      - name: Run Mypy
        run: pixi run mypy .

      - name: Run Pytest
        run: pixi run test
